package com.example.perfulandia.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.example.perfulandia.data.local.SessionManager
import com.example.perfulandia.data.repository.CategoryRepository
import com.example.perfulandia.data.repository.PerfumeRepository
import com.example.perfulandia.model.Category
import com.example.perfulandia.model.Perfume
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch

enum class SubmissionStatus {
    IDLE,
    SUBMITTING,
    SUCCESS,
    ERROR
}

data class CreatePerfumeUiState(
    val categories: List<Category> = emptyList(),
    val submissionStatus: SubmissionStatus = SubmissionStatus.IDLE,
    val error: String? = null
)

class CreatePerfumeViewModel(
    private val perfumeRepository: PerfumeRepository,
    private val categoryRepository: CategoryRepository,
    private val sessionManager: SessionManager
) : ViewModel() {

    private val _uiState = MutableStateFlow(CreatePerfumeUiState())
    val uiState: StateFlow<CreatePerfumeUiState> = _uiState.asStateFlow()

    init {
        fetchCategories()
    }

    private fun fetchCategories() {
        viewModelScope.launch {
            try {
                val categoriesResult = categoryRepository.getAllCategories()
                _uiState.update { it.copy(categories = categoriesResult.getOrThrow()) }
            } catch (e: Exception) {
                _uiState.update { it.copy(error = "Error al cargar categorías") }
            }
        }
    }

    fun createPerfume(
        nombre: String,
        marca: String,
        fragancia: String,
        tamano: Int?,
        genero: String,
        precio: Double,
        stock: Int,
        categoriaId: String,
        descripcion: String,
        imagen: String
    ) {
        viewModelScope.launch {
            _uiState.update { it.copy(submissionStatus = SubmissionStatus.SUBMITTING) }
            try {
                val perfume = Perfume(
                    id = "", // ID is empty because it will be generated by the backend
                    nombre = nombre,
                    marca = marca,
                    fragancia = fragancia,
                    tamano = tamano,
                    genero = genero,
                    precio = precio,
                    stock = stock,
                    categoriaId = categoriaId,
                    descripcion = descripcion,
                    imagen = imagen,
                    imagenThumbnail = imagen // Use the same image for thumbnail for simplicity
                )
                perfumeRepository.createPerfume(perfume)
                _uiState.update { it.copy(submissionStatus = SubmissionStatus.SUCCESS) }
            } catch (e: Exception) {
                _uiState.update {
                    it.copy(
                        submissionStatus = SubmissionStatus.ERROR,
                        error = e.message
                    )
                }
            }
        }
    }

    fun logout() {
        viewModelScope.launch {
            sessionManager.clearSession()
        }
    }

    fun resetSubmissionStatus() {
        _uiState.update { it.copy(submissionStatus = SubmissionStatus.IDLE, error = null) }
    }
}

class CreatePerfumeViewModelFactory(
    private val perfumeRepository: PerfumeRepository,
    private val categoryRepository: CategoryRepository,
    private val sessionManager: SessionManager
) : ViewModelProvider.Factory {
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        if (modelClass.isAssignableFrom(CreatePerfumeViewModel::class.java)) {
            @Suppress("UNCHECKED_CAST")
            return CreatePerfumeViewModel(perfumeRepository, categoryRepository, sessionManager) as T
        }
        throw IllegalArgumentException("Unknown ViewModel class")
    }
}